# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup current release version from tag
        id: release_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=release_version::${GITHUB_REF:11}
      - name: Prepare gradle version param
        id: version_param
        run: echo ::set-output name=version_param::${{ (steps.release_version.outputs.release_version != null && format('-Pversion={0}', steps.release_version.outputs.release_version)) || '' }}
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            ${{ steps.version_param.outputs.version_param }}
            publishToSonatype
            closeAndReleaseSonatypeStagingRepository
          cache-read-only: true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          RELEASE: true
      - name: Add artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
